/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'docs-category',
    {
      type: 'category',
      label: 'React.js',
      items: ['Frontend/React.js/index']
    },
    {
      type: 'category',
      label: 'Golang',
      items: ['Backend/Golang/index']
    },
    {
      type: 'category',
      label: 'Others',
      link: {
        type: 'generated-index',
        title: 'Others',
        slug: '/others',
        keywords: ['VS Code']
      },
      items: [
        {
          type: 'category',
          label: 'Visual Studio Code',
          link: {
            type: 'doc',
            id: 'Visual Studio Code/index'
          },
          items: [
            'Visual Studio Code/Keyboard shortcuts'
          ]
        }
      ]
    }
  ]
};

module.exports = sidebars;
